### PUT request to update an existing patient infos
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "YYYYYY Sadek Belkhiria UPDATED",
  "email": "belkhiriasadek@gmail.com",
  "address": "Rue Abu Taib Moutanabi",
  "dateOfBirth": "1999-04-24"
}
###